library(xlsx)


# idea based on significance_testing paper

options(digits = 5)



# this function takes a list of prediction vectors generated by different models
# and an evaluation vector and calculates the mcnemar test value on every paired prediction

testdifference = function(sentitest, preds){
  l = length(preds)
  for(i in 1:(l - 1)){
    for(j in (i+1):l){
      model1 = unlist(preds[i])
      model2 = unlist(preds[j])
      
      bothtrue = sum((sentitest == model1) & (sentitest == model2))
      trueA = sum((sentitest == model1) & (sentitest != model2))
      trueB = sum((sentitest != model1) & (sentitest == model2))
      bothfalse = sum((sentitest != model1) & (sentitest != model2))
      
      tabone = c(bothfalse, trueA)
      tabtwo = c(trueB, bothtrue)
      
      misscl.table = cbind(tabone, tabtwo)
      mcn = mcnemar.test(misscl.table)
      print(mcn)
    }
  }
  return("finished")
}


preds = list(pda.preds5, pda.preds127, pda.preds658)
testdifference(sentitest, preds)





# get acc, kappa, sens, spec for every model on different subfeatures

options(digits =4)

features_5 = c(round(C5.0.conf5$overall, 4)[c(1,2)], round(C5.0.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(C5.0.conf127$overall,4)[c(1,2)], round(C5.0.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(C5.0.conf658$overall, 4)[c(1,2)], round(C5.0.conf658$byClass, 4)[c(1,2)])

c5.0.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(c5.0.perf, file = "c5.0_feature_perf.xlsx")




features_5 = c(round(gbm.conf5$overall, 4)[c(1,2)], round(gbm.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(gbm.conf127$overall,4)[c(1,2)], round(gbm.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(gbm.conf658$overall, 4)[c(1,2)], round(gbm.conf658$byClass, 4)[c(1,2)])

gbm.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(gbm.perf, file = "gbm_feature_perf.xlsx")




features_5 = c(round(linsvm.conf5$overall, 4)[c(1,2)], round(linsvm.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(linsvm.conf127$overall,4)[c(1,2)], round(linsvm.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(linsvm.conf658$overall, 4)[c(1,2)], round(linsvm.conf658$byClass, 4)[c(1,2)])

linsvm.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(linsvm.perf, file = "linsvm_feature_perf.xlsx")



features_5 = c(round(nnet.conf5$overall, 4)[c(1,2)], round(nnet.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(nnet.conf127$overall,4)[c(1,2)], round(nnet.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(nnet.conf658$overall, 4)[c(1,2)], round(nnet.conf658$byClass, 4)[c(1,2)])

nnet.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(nnet.perf, file = "nnet_feature_perf.xlsx")



features_5 = c(round(nb.conf5$overall, 4)[c(1,2)], round(nb.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(nb.conf127$overall,4)[c(1,2)], round(nb.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(nb.conf658$overall, 4)[c(1,2)], round(nb.conf658$byClass, 4)[c(1,2)])

nb.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(nb.perf, file = "nb_feature_perf.xlsx")



features_5 = c(round(rf.conf5$overall, 4)[c(1,2)], round(rf.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(rf.conf127$overall,4)[c(1,2)], round(rf.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(rf.conf658$overall, 4)[c(1,2)], round(rf.conf658$byClass, 4)[c(1,2)])

rf.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(rf.perf, file = "rf_feature_perf.xlsx")



features_5 = c(round(treebag.conf5$overall, 4)[c(1,2)], round(treebag.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(treebag.conf127$overall,4)[c(1,2)], round(treebag.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(treebag.conf658$overall, 4)[c(1,2)], round(treebag.conf658$byClass, 4)[c(1,2)])

treebag.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(treebag.perf, file = "treebag_feature_perf.xlsx")




features_5 = c(round(pda.conf5$overall, 4)[c(1,2)], round(pda.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(pda.conf127$overall,4)[c(1,2)], round(pda.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(pda.conf658$overall, 4)[c(1,2)], round(pda.conf658$byClass, 4)[c(1,2)])

glmn.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(glmn.perf, file = "pda_feature_perf.xlsx")




features_5 = c(round(glmn.conf5$overall, 4)[c(1,2)], round(glmn.conf5$byClass, 4)[c(1,2)])
features_127 = c(round(glmn.conf127$overall,4)[c(1,2)], round(glmn.conf127$byClass, 4)[c(1,2)])
features_658 = c(round(glmn.conf658$overall, 4)[c(1,2)], round(glmn.conf658$byClass, 4)[c(1,2)])

glmn.perf = data.frame(rbind(features_5, features_127, features_658))

write.xlsx(glmn.perf, file = "glmn_feature_perf.xlsx")





round(gbm.conf5$overall, 4)
round(gbm.conf127$overall,4)
round(gbm.conf658$overall, 4)

round(linsvm.conf5$overall, 4)
round(linsvm.conf127$overall,4)
round(linsvm.conf658$overall, 4)

round(nnet.conf5$overall, 4)
round(nnet.conf127$overall,4)
round(nnet.conf658$overall, 4)

round(nb.conf5$overall, 4)
round(nb.conf127$overall,4)
round(nb.conf658$overall, 4)

round(rf.conf5$overall, 4)
round(rf.conf127$overall,4)
round(rf.conf658$overall, 4)

round(treebag.conf5$overall, 4)
round(treebag.conf127$overall,4)
round(treebag.conf658$overall, 4)

round(glmn.conf5$overall, 4)
round(glmn.conf127$overall,4)
round(glmn.conf658$overall, 4)





